[package]
name = "k2tree"
version = "0.1.0"
edition = "2021"

[dependencies]
lru = "0.12"

[dev-dependencies]
criterion = "0.5"
rand = "0.8"

[[bench]]
name = "k2tree_bench"
harness = false

[[bench]]
name = "count_bench"
harness = false

[[bench]]
name = "get_bench"
harness = false

[[bench]]
name = "lru_bench"
harness = false

[[bench]]
name = "insert_four_bench"
harness = false
